// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbLSpHJwqt1PfLEe6z_nRqWp-u5IBDu7s',
    appId: '1:906995190143:web:571e562691d1a0f7a0f24a',
    messagingSenderId: '906995190143',
    projectId: 'zalo-app-641d4',
    authDomain: 'zalo-app-641d4.firebaseapp.com',
    storageBucket: 'zalo-app-641d4.firebasestorage.app',
    measurementId: 'G-SXVSCKX6X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8R-F5SW5bDhMbfM5Jd1bKoN1gA16UmY',
    appId: '1:906995190143:android:acf689b79e5a4810a0f24a',
    messagingSenderId: '906995190143',
    projectId: 'zalo-app-641d4',
    storageBucket: 'zalo-app-641d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAoPE59iBGdj0XFhxfhHXkxuhAnUgHpGk',
    appId: '1:906995190143:ios:4250c1bb4124365ea0f24a',
    messagingSenderId: '906995190143',
    projectId: 'zalo-app-641d4',
    storageBucket: 'zalo-app-641d4.firebasestorage.app',
    iosBundleId: 'com.example.zalo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAoPE59iBGdj0XFhxfhHXkxuhAnUgHpGk',
    appId: '1:906995190143:ios:4250c1bb4124365ea0f24a',
    messagingSenderId: '906995190143',
    projectId: 'zalo-app-641d4',
    storageBucket: 'zalo-app-641d4.firebasestorage.app',
    iosBundleId: 'com.example.zalo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbLSpHJwqt1PfLEe6z_nRqWp-u5IBDu7s',
    appId: '1:906995190143:web:a3f7a477a47e757da0f24a',
    messagingSenderId: '906995190143',
    projectId: 'zalo-app-641d4',
    authDomain: 'zalo-app-641d4.firebaseapp.com',
    storageBucket: 'zalo-app-641d4.firebasestorage.app',
    measurementId: 'G-YCN1GH759P',
  );
}
