name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-2004

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests (optional)
      - name: Run tests
        run: flutter test

      # Build APK (for Android)
      - name: Build APK
        run: flutter build apk --release

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: zalo_flutter.apk
          path: build/app/outputs/flutter-apk/app-release.apk
